version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - run:
          name: Hugo version
          command: echo "$(hugo version)"
      - add_ssh_keys:
          fingerprints:
            - "95:ec:92:31:a6:22:26:fe:93:0e:f3:6f:55:d0:0f:7c"
      - checkout
      - deploy:
          name: Deploy to GitHub Pages
          command: |
              ./.circleci/deploy.sh
