version: 2
jobs:
  build:
    branches:
      only:
        #- master
        - campcar
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - run:
          name: Hugo version
          command: echo "$(hugo version)"
      - add_ssh_keys:
          fingerprints:
            - "0a:c8:50:24:aa:25:82:e6:fe:e7:88:d4:d3:db:f9:79"
      - checkout
      - deploy:
          name: Deploy to GitHub Pages
          command: |
              ./.circleci/deploy.sh
