version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - run:
          name: Hugo version
          command: echo "$(hugo version)"
      - deploy:
          name: Deploy to GitHub Pages
          command: ./.circleci/deploy.sh
