baseurl = "https://kimujinyogi.github.io/"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
theme = "terminal"
paginate = 5
googleAnalytics = "UA-139531645-1"
disqusShortname = "kimujinyogi-github-io-1"

[taxonomies]
  tag = "tags"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # サイト名
  site_name = "じにょぎの日常"
  # 名前
  author = "jinyogi"
  # description
  description = "旅行 キャンピングカー ヴォーンDC ノイン WHON DC NEUN"

[languages]
  [languages.ja]
    title = "じにょぎの日常"
    subtitle = "日常生活の何かをつぶやく"
    keywords = "キャンピングカー"
    copyright = "kimujinyogi@gmail.com"
    menuMore = "メニュー展開"
    readMore = "さらに表示"
    readOtherPosts = "他の記事を確認"

    [languages.ja.params.logo]
      logoText = "じにょぎの日常"
      logoHomeLink = "/"

    [languages.ja.menu]
      [[languages.ja.menu.main]]
        identifier = "Home"
		weight = 1
        name = "ホーム"
        url = "/"
      [[languages.ja.menu.main]]
        identifier = "tags"
		weight = 2
        name = "タグリスト"
        url = "/tags"
      [[languages.ja.menu.main]]
        identifier = "mywife"
		weight = 3
        name = "妻のブログ"
        url = "https://ameblo.jp/9-miho/"
      [[languages.ja.menu.main]]
        identifier = "About"
		weight = 4
        name = "じにょぎについて"
        url = "/about"
      [[languages.ja.menu.main]]
        identifier = "Privacy"
		weight = 5
        name = "プライバシーポリシー"
        url = "/privacy"
