baseurl = "https://kimujinyogi.github.io/"
languageCode = "ja"
defaultContentLanguage = "ja"
theme = "terminal"
paginate = 5
googleAnalytics = "UA-139531645-1"
disqusShortname = "kimujinyogi-github-io-1"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = false
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # サイト名
  site_name = "じにょぎの日常"
  # 名前
  author = "jinyogi"
  # description
  description = "旅行 キャンピングカー ヴォーンDC ノイン WHON DC NEUN"

[languages]
  [languages.ja]
    title = "じにょぎの日常"
    subtitle = "日常生活の何かをつぶやく"
    keywords = "キャンピングカー"
    copyright = "kimujinyogi@gmail.com"
    menuMore = "メニュー展開"
    readMore = "さらに表示"
    readOtherPosts = "他の記事を確認"

    [languages.ja.params.logo]
      logoText = "じにょぎの日常"
      logoHomeLink = "/"

    [languages.ja.menu]
      [[languages.ja.menu.main]]
        identifier = "About"
        name = "じにょぎについて"
        url = "/about"
      [[languages.ja.menu.main]]
        identifier = "mywife"
        name = "妻のブログ"
        url = "https://ameblo.jp/9-miho/"
